### PR TITLE
Figwheeled and upgraded.

### PR DESCRIPTION
**Pull request by fdserr**
Since I wanted to try it within a figwheel project, here's the resulting patch if you care, with upgraded deps. 
To try it out, lein install from main project dir, then lein figwheel from example dir.
Made it a 1.1.4-SNAPSHOT, you may want to adjust both project.clj as you see fit.
Awesome lib again. Mucho thankies!

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch. What's the advantage of using Figwheel in the example project? Is it just for changing the example data around in real time?

**Comment by fdserr** [comment]
Changing values is obviously trivial. Needed to assert open/close state behaviour in a reloaded env, since we'd never do cljs without fw. 2 possibilities: start a fresh project, set deps, copy/paste code; or use the example. Thought it might be useful to other fw users... up to you^

**Comment by weavejester** [comment]
I think I might pass on this PR. There are quite a few things that would need to be changed before I could merge.

The commit messages would need to be changed to be consistent with the project's commit history; the version number change would need to be rolled back; the updated dependencies would need to be moved to a separate PR; the Clojure version would need to be changed back; the comments and whitespace in the example project file would need to be removed; the extra stylesheet would probably need to go; the user namespace probably isn't necessary either.

So the work required probably outweighs the benefit in this case... But you're certainly welcome to move the updated example project into a repository of your own.

**Comment by fdserr** [comment]
Sure, no problem.

**Pull request closed without merging**
